#!/bin/bash

if [ ! -f $1 ]
then 
    echo -e "#include <iostream>\n#include <string>\n#include <cstring>\n#include <algorithm>\n#include <sstream>\n#include <cstdio>\n#include <cstdlib>\n#include <vector>\n#include <cmath>\n#include<stack>\n\nusing namespace std;\n\nint main()\n{\n\treturn 0;\n}" > $1
    vim $1
    #gedit $1 &
else
    echo $1 exists.
fi
