#!/bin/bash

echo -e "#include <iostream>\n#include <string>\n#include <cstring>\n#include <algorithm>\n#include <sstream>\n#include <cstdio>\n#include <cstdlib>\n#include <vector>\n\nusing namespace std;\n\nint main()\n{\n\treturn 0;\n}" > $1
